params:
  # defaultTheme: light
 defaultTheme: "dark"
 description: "一个描述"
 # defaultTheme: auto 
 ShowShareButtons: true
 socialIcons: # optional
  - name: "telegram"
    url: "https://t.me/NanoSpook"
 env: "production"