baseURL = "https://spook.vercel.app/"
# languageCode = "zh-CN"
defaultContentLanguage = "cn"
title = "Spook's Blog"
theme = "hugo-PaperMod"

#分页
Paginate = 5

#emoji
enableEmoji = true
defaultTheme= "dark"
ShowShareButtons= true

[params]
    ShowReadingTime= true
    ShowShareButtons= true
[socialIcons]
    name= github
    url= 'https://github.com/'
