baseURL = "https://spook.vercel.app/"
# languageCode = "zh-CN"
defaultContentLanguage = "cn"
title = "Spook's Blog"
theme = "hugo-PaperMod"

#分页
Paginate = 5

#emoji
enableEmoji = true

[[params.social]]
name = "email"
url  = "mailto:nanospook@qq.com"

[[params.social]]
name = "telegram"
url  = "https://t.me/NanoSpook"

